// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAI7AqohVE1Suh-QOVq6lIV-QotjQQAQSU',
    appId: '1:573478722452:web:9026d02d874437b8720d81',
    messagingSenderId: '573478722452',
    projectId: 'vendapp-2e5cc',
    authDomain: 'vendapp-2e5cc.firebaseapp.com',
    storageBucket: 'vendapp-2e5cc.appspot.com',
    measurementId: 'G-N5SCKWDL38',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvLmAzCxCvIOoiAJDaKNL6Ez1P4gF5XSo',
    appId: '1:573478722452:android:37ccbe811f718cef720d81',
    messagingSenderId: '573478722452',
    projectId: 'vendapp-2e5cc',
    storageBucket: 'vendapp-2e5cc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7Yh1yovI0DL7Mbygb6QJtoOcu3b7crIY',
    appId: '1:573478722452:ios:0d96450d6196ce3b720d81',
    messagingSenderId: '573478722452',
    projectId: 'vendapp-2e5cc',
    storageBucket: 'vendapp-2e5cc.appspot.com',
    iosBundleId: 'com.example.vendApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7Yh1yovI0DL7Mbygb6QJtoOcu3b7crIY',
    appId: '1:573478722452:ios:0d96450d6196ce3b720d81',
    messagingSenderId: '573478722452',
    projectId: 'vendapp-2e5cc',
    storageBucket: 'vendapp-2e5cc.appspot.com',
    iosBundleId: 'com.example.vendApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAI7AqohVE1Suh-QOVq6lIV-QotjQQAQSU',
    appId: '1:573478722452:web:3de9a53805b02d5a720d81',
    messagingSenderId: '573478722452',
    projectId: 'vendapp-2e5cc',
    authDomain: 'vendapp-2e5cc.firebaseapp.com',
    storageBucket: 'vendapp-2e5cc.appspot.com',
    measurementId: 'G-6PM9KB8V0V',
  );

}